# 参考：https://spec.api.metro.tokyo.lg.jp/spec/t001001d0000000001-1db9fd22025886d3d5c9607d5c24fdf0-0
openapi: 3.1.0
info:
  title: 東京ビッグサイトのイベント情報 API
  summary: 東京ビッグサイト10月～12月のイベント情報
  version: 1.0.0

paths:
  /t001001d0000000001-1db9fd22025886d3d5c9607d5c24fdf0-0/json:
    post:
      operationId: postBigSite
      summary: 東京ビッグサイト10月～12月のイベント情報を取得する
      parameters:
        - name: limit
          in: query
          description: >
            **1回のAPI呼び出しで取得するデータ件数の上限を指定します**<br>
            この画面でのデフォルト値は5です。<br>
            APIを直接呼び出す場合のデフォルトは100が設定されます。最小値は0、最大値は1000です。
          schema:
            type: integer
            minimum: 0
            maximum: 1000
            default: 5
        - name: offset
          in: query
          description: >
            **データの取得開始位置を指定します**<br>
            一定件数毎に分けてデータを取得する場合に利用します。
          schema:
            type: integer
      requestBody:
        required: true
        description: >
          **詳細な絞り込み検索をする場合に本項目を指定してください**<br>
          `Example Value`に指定例が表示されます。指定可能な内容を参照する場合は`Schema`を押してください。<br>
          `>`を押すと折りたたまれた内容が表示されます。<br>
          なお、初期表示で入力されている指定例のまま`Execute`ボタンを押下しても（`Code 400`：リクエストパラメータ不正）となります。<br>
          簡単に実行するためには`requestBody`の中身を`{}`とすることでエラーなく取得することができます。
        content:
          application/json:
            schema:
              type: object
              properties:
                column:
                  type: array
                  items:
                    $ref: "#/components/schemas/Column"
                searchCondition:
                  description: >
                    **絞り込み条件を指定します**
                  $ref: "#/components/schemas/SearchCondition"
                sortOrder:
                  $ref: "#/components/schemas/SortOrder"
      responses:
        "200":
          description: 処理が正常に終了しました
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: 検索結果の総件数です。limitおよびoffsetを考慮しない検索結果の件数を表示します
                  subtotal:
                    type: integer
                    description: 検索結果のうち今回のレスポンスで返却している件数です
                  limit:
                    type: [integer, "null"]
                    description: リクエスト時に指定した値が設定されます
                  offset:
                    type: [integer, "null"]
                    description: リクエスト時に指定した値が設定されます
                  metadata:
                    $ref: "#/components/schemas/ResponseMetadata"
                  hits:
                    type: array
                    items:
                      $ref: "#/components/schemas/ResponseHit"
                required:
                  - total
                  - subtotal
                  - limit
                  - offset
                  - metadata
                  - hits
        "400":
          description: リクエストパラメータが不正です
          # content:
          #   application/json:
          #     schema:
          #       type: object
          #       properties:
          #         message:
          #           type: string
          #           description: エラー内容の説明テキスト
          #       required:
          #         - message
        "405":
          description: APIが無効化されています
        "500":
          description: 内部エラーが発生しました

components:
  schemas:
    SortOrder:
      description: >
        ソート順序を指定します。指定可能な項目は以下の通りです
          * asc - 昇順
          * desc - 降順
      type: string
      enum:
        - asc
        - desc
      default: asc

    Column:
      type: string
      enum:
        - 展示会名
        - 会期(開始)
        - 開始曜日
        - 会期(終了)
        - 終了曜日
        - 利用施設
        - 開催時間
        - 最終日の終了時刻(●:30分前に終了　▲:1時間前に終了　■:2時間前に終了)
        - 来場対象者
        - 入場料について
        - 内容
        - 連絡先
        - TEL
        - URL

    StringRelationship:
      description: >
        項目名と条件の関係を指定します。指定可能な項目は以下の通りです
          * eq - イコール
          * contains - 含む
          * startsWith - で始まる
          * endsWith - で終わる
      type: string
      enum:
        - eq
        - contains
        - startsWith
        - endsWith

    NumericRelationship:
      description: >
        項目名と条件の関係を指定します。指定可能な項目は以下の通りです
          * eq - イコール
          * le - 以下
          * lt - より小さい
          * ge - 以上
          * gt - より大きい
      type: string
      enum:
        - eq
        - le
        - lt
        - ge
        - gt

    DateRelationship:
      description: >
        項目名と条件の関係を指定します。指定可能な項目は以下の通りです
          * eq - イコール
          * le - 以下
          * lt - より小さい
          * ge - 以上
          * gt - より大きい
      type: string
      enum:
        - eq
        - le
        - lt
        - ge
        - gt

    ConditionRelationship:
      description: >
        `stringAndSearch`、`stringOrSearch`、`numericAndSearch`、`numericOrSearch`、`dateAndSearch`、`dateOrSearch`、`datetimeAndSearch`、`datetimeOrSearch`の間の絞り込み条件の関係を指定します。指定可能な項目は以下の通りです
          * and - and条件(デフォルト)
          * or - or条件
      type: string
      enum:
        - and
        - or
      default: and

    SearchCondition:
      type: object
      properties:
        conditionRelationship:
          $ref: "#/components/schemas/ConditionRelationship"
        stringAndSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/StringRelationship"
              condition:
                type: string
        stringOrSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/StringRelationship"
              condition:
                type: string
        numericAndSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/NumericRelationship"
              condition:
                type: string
        numericOrSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/NumericRelationship"
              condition:
                type: string
        dateAndSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/DateRelationship"
              condition:
                type: string
        dateOrSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/DateRelationship"
              condition:
                type: string
        datetimeAndSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/DateRelationship"
              condition:
                type: string
        datetimeOrSearch:
          type: array
          items:
            type: object
            properties:
              column:
                $ref: "#/components/schemas/Column"
              relationship:
                $ref: "#/components/schemas/DateRelationship"
              condition:
                type: string
    ResponseMetadata:
      type: object
      properties:
        apiId:
          type: string
          description: apiId
        title:
          type: string
          description: API名
        datasetId:
          type: string
          description: データセットID
        datasetTitle:
          type: string
          description: データセットタイトル
        datasetDesc:
          type: string
          description: データセット説明
        dataTitle:
          type: string
          description: データタイトル
        dataDesc:
          type: string
          description: データ説明
        sheetname:
          type: string
          description: シート名
        version:
          type: string
          description: 本APIのデータバージョンを示します。データの更新に合わせてバージョンも更新されます
        created:
          type: string
          format: date
          description: 作成日
        updated:
          type: string
          format: date
          description: 更新日
    ResponseHit:
      type: object
      properties:
        row:
          type: integer
        展示会名:
          type: string
        会期(開始):
          type: string
          format: date
        開始曜日:
          $ref: "#/components/schemas/Weekday"
        会期(終了):
          type: string
          format: date
        終了曜日:
          $ref: "#/components/schemas/Weekday"
        利用施設:
          type: string
        開催時間:
          type: string
        最終日の終了時刻(●:30分前に終了　▲:1時間前に終了　■:2時間前に終了):
          $ref: "#/components/schemas/EndTimeMark"
        来場対象者:
          $ref: "#/components/schemas/VisitorType"
        入場料について:
          type: string
        内容:
          type: string
        連絡先:
          type: string
        TEL:
          type: string
        URL:
          type: string
    Weekday:
      type: string
      enum:
        - 月
        - 火
        - 水
        - 木
        - 金
        - 土
        - 日
    EndTimeMark:
      type: string
      enum:
        - ""
        - "●"
        - "▲"
        - "■"
    VisitorType:
      type: string
      enum:
        - 商談
        - 一般
        - 商談/一般
