/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * 東京ビッグサイトのイベント情報 API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";
import axios from "axios";

import type { Key } from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";

/**
 * ソート順序を指定します。指定可能な項目は以下の通りです
  * asc - 昇順
  * desc - 降順

 */
export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortOrder = {
  asc: "asc",
  desc: "desc",
} as const;

export type Column = (typeof Column)[keyof typeof Column];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Column = {
  展示会名: "展示会名",
  "会期(開始)": "会期(開始)",
  開始曜日: "開始曜日",
  "会期(終了)": "会期(終了)",
  終了曜日: "終了曜日",
  利用施設: "利用施設",
  開催時間: "開催時間",
  "最終日の終了時刻(●:30分前に終了_▲:1時間前に終了_■:2時間前に終了)":
    "最終日の終了時刻(●:30分前に終了　▲:1時間前に終了　■:2時間前に終了)",
  来場対象者: "来場対象者",
  入場料について: "入場料について",
  内容: "内容",
  連絡先: "連絡先",
  TEL: "TEL",
  URL: "URL",
} as const;

/**
 * 項目名と条件の関係を指定します。指定可能な項目は以下の通りです
  * eq - イコール
  * le - 以下
  * lt - より小さい
  * ge - 以上
  * gt - より大きい

 */
export type Relationship = (typeof Relationship)[keyof typeof Relationship];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Relationship = {
  eq: "eq",
  le: "le",
  lt: "lt",
  ge: "ge",
  gt: "gt",
} as const;

/**
 * `stringAndSearch`、`stringOrSearch`、`numericAndSearch`、`numericOrSearch`、`dateAndSearch`、`dateOrSearch`、`datetimeAndSearch`、`datetimeOrSearch`の間の絞り込み条件の関係を指定します。指定可能な項目は以下の通りです
  * and - and条件(デフォルト)
  * or - or条件

 */
export type ConditionRelationship =
  (typeof ConditionRelationship)[keyof typeof ConditionRelationship];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConditionRelationship = {
  and: "and",
  or: "or",
} as const;

export type SearchConditionStringAndSearchItem = {
  column?: Column;
  relationship?: Relationship;
  condition?: string;
};

export type SearchConditionStringOrSearchItem = {
  column?: Column;
  relationship?: Relationship;
  condition?: string;
};

export interface SearchCondition {
  conditionRelationship?: ConditionRelationship;
  stringAndSearch?: SearchConditionStringAndSearchItem[];
  stringOrSearch?: SearchConditionStringOrSearchItem[];
}

export type PostBigSiteParams = {
  /**
   * 1回のAPI呼び出しで取得するデータ件数の上限を指定します
   * @minimum 0
   * @maximum 1000
   */
  limit?: number;
  /**
   * データの取得開始位置を指定します
   */
  offset?: number;
};

export type PostBigSiteBodySearchCondition = { [key: string]: unknown };

export type PostBigSiteBody = {
  column?: Column;
  searchCondition?: PostBigSiteBodySearchCondition;
  sortOrder?: SortOrder;
};

/**
 * @summary 東京ビッグサイト10月～12月のイベント情報を取得する
 */
export const postBigSite = (
  postBigSiteBody: PostBigSiteBody,
  params?: PostBigSiteParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.post(
    `https://service.api.metro.tokyo.lg.jp/api/t001001d0000000001-1db9fd22025886d3d5c9607d5c24fdf0-0/json`,
    postBigSiteBody,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

export const getPostBigSiteMutationFetcher = (
  params?: PostBigSiteParams,
  options?: AxiosRequestConfig,
) => {
  return (
    _: Key,
    { arg }: { arg: PostBigSiteBody },
  ): Promise<AxiosResponse<unknown>> => {
    return postBigSite(arg, params, options);
  };
};
export const getPostBigSiteMutationKey = (params?: PostBigSiteParams) =>
  [
    `https://service.api.metro.tokyo.lg.jp/api/t001001d0000000001-1db9fd22025886d3d5c9607d5c24fdf0-0/json`,
    ...(params ? [params] : []),
  ] as const;

export type PostBigSiteMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBigSite>>
>;
export type PostBigSiteMutationError = AxiosError<unknown>;

/**
 * @summary 東京ビッグサイト10月～12月のイベント情報を取得する
 */
export const usePostBigSite = <TError = AxiosError<unknown>>(
  params?: PostBigSiteParams,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postBigSite>>,
      TError,
      Key,
      PostBigSiteBody,
      Awaited<ReturnType<typeof postBigSite>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  },
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostBigSiteMutationKey(params);
  const swrFn = getPostBigSiteMutationFetcher(params, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
