/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * ユーザー API
 * OpenAPI spec version: 1.0.0
 */

import { faker } from "@faker-js/faker";
import { delay, HttpResponse, http } from "msw";
import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";

import { customFetch } from "../../openapi/custom-fetch";
export interface User {
  id?: number;
  name?: string;
}

export interface UserInput {
  name?: string;
}

export interface ErrorResponse {
  message?: string;
}

export type GetUsersParams = {
  /**
   * Page number (starting from 1)
   * @minimum 1
   */
  page?: number;
  /**
   * Number of users per page
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
};

export type GetUsers200 = {
  /** Total number of users */
  total?: number;
  /** Current page number */
  page?: number;
  /** Number of users per page */
  pageSize?: number;
  users?: User[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all users
 */
export type getUsersResponse200 = {
  data: GetUsers200;
  status: 200;
};

export type getUsersResponse500 = {
  data: ErrorResponse;
  status: 500;
};

export type getUsersResponseComposite =
  | getUsersResponse200
  | getUsersResponse500;

export type getUsersResponse = getUsersResponseComposite & {
  headers: Headers;
};

export const getGetUsersUrl = (params?: GetUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users?${stringifiedParams}`
    : `/api/users`;
};

export const getUsers = async (
  params?: GetUsersParams,
  options?: RequestInit,
): Promise<getUsersResponse> => {
  return customFetch<getUsersResponse>(getGetUsersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetUsersKey = (params?: GetUsersParams) =>
  [`/api/users`, ...(params ? [params] : [])] as const;

export type GetUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsers>>
>;
export type GetUsersQueryError = ErrorResponse;

/**
 * @summary Get all users
 */
export const useGetUsers = <TError = ErrorResponse>(
  params?: GetUsersParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getUsers>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetUsersKey(params) : null));
  const swrFn = () => getUsers(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Create a new user
 */
export type createUserResponse201 = {
  data: User;
  status: 201;
};

export type createUserResponseComposite = createUserResponse201;

export type createUserResponse = createUserResponseComposite & {
  headers: Headers;
};

export const getCreateUserUrl = () => {
  return `/api/users`;
};

export const createUser = async (
  userInput: UserInput,
  options?: RequestInit,
): Promise<createUserResponse> => {
  const res = await fetch(getCreateUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(userInput),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: createUserResponse["data"] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createUserResponse;
};

export const getCreateUserMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UserInput }): Promise<createUserResponse> => {
    return createUser(arg, options);
  };
};
export const getCreateUserMutationKey = () => [`/api/users`] as const;

export type CreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>;
export type CreateUserMutationError = Promise<unknown>;

/**
 * @summary Create a new user
 */
export const useCreateUser = <TError = Promise<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    Key,
    UserInput,
    Awaited<ReturnType<typeof createUser>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateUserMutationKey();
  const swrFn = getCreateUserMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Delete a user by ID
 */
export type deleteUserResponse204 = {
  data: null;
  status: 204;
};

export type deleteUserResponseComposite = deleteUserResponse204;

export type deleteUserResponse = deleteUserResponseComposite & {
  headers: Headers;
};

export const getDeleteUserUrl = (id: number) => {
  return `/api/users/${id}`;
};

export const deleteUser = async (
  id: number,
  options?: RequestInit,
): Promise<deleteUserResponse> => {
  const res = await fetch(getDeleteUserUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deleteUserResponse["data"] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteUserResponse;
};

export const getDeleteUserMutationFetcher = (
  id: number,
  options?: RequestInit,
) => {
  return (_: Key, __: { arg: Arguments }): Promise<deleteUserResponse> => {
    return deleteUser(id, options);
  };
};
export const getDeleteUserMutationKey = (id: number) =>
  [`/api/users/${id}`] as const;

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>;
export type DeleteUserMutationError = Promise<unknown>;

/**
 * @summary Delete a user by ID
 */
export const useDeleteUser = <TError = Promise<unknown>>(
  id: number,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteUser>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  },
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteUserMutationKey(id);
  const swrFn = getDeleteUserMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const getGetUsersResponseMock = (
  overrideResponse: Partial<GetUsers200> = {},
): GetUsers200 => ({
  total: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    undefined,
  ]),
  page: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    undefined,
  ]),
  pageSize: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    undefined,
  ]),
  users: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({
          min: undefined,
          max: undefined,
          multipleOf: undefined,
        }),
        undefined,
      ]),
      name: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCreateUserResponseMock = (
  overrideResponse: Partial<User> = {},
): User => ({
  id: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined, multipleOf: undefined }),
    undefined,
  ]),
  name: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetUsersMockHandler = (
  overrideResponse?:
    | GetUsers200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetUsers200> | GetUsers200),
) => {
  return http.get("*/users", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUsersResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getCreateUserMockHandler = (
  overrideResponse?:
    | User
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<User> | User),
) => {
  return http.post("*/users", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateUserResponseMock(),
      ),
      { status: 201, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDeleteUserMockHandler = (
  overrideResponse?:
    | null
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<null> | null),
) => {
  return http.delete("*/users/:id", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};
export const getApiMock = () => [
  getGetUsersMockHandler(),
  getCreateUserMockHandler(),
  getDeleteUserMockHandler(),
];
